export const SUPPORTED_CURRENCIES = ['BTC', 'ETH', 'DOGE'];

export const PRICE_ALERT_TYPES = {
  ABOVE: 'PRICE_ABOVE',
  BELOW: 'PRICE_BELOW',
  PERCENT_CHANGE: 'PERCENT_CHANGE',
};

export const WEBSOCKET_EVENTS = {
  PRICE_UPDATE: 'PRICE_UPDATE',
  PRICE_ALERT: 'PRICE_ALERT',
  WALLET_UPDATE: 'WALLET_UPDATE',
};
